### ISSUE TITLE
The Style Guide seems still use former favicon

### ISSUE THREAD

**Issue by gizmecano** [freeCodeCamp/design-style-guide#40]
While the former green logo seems to have disappeared from the [main site](https://www.freecodecamp.org/), it seems to be paradoxically still used as [favicons](https://github.com/freeCodeCamp/design-style-guide/blob/6814b38fa7c1938884a425443a247ae7c04a6a9c/index.html#L47-L193) for the [Style Guide page](https://design-style-guide.freecodecamp.org/). I suppose using this shortcut icons could be just an oversight because otherwise it would seem a bit strange...

**Comment by ahmaxed** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/issues/38540
