### ISSUE TITLE
I submitted freeCodeCamp to brandcolors.net

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/design-style-guide#9]
I submitted the following colors to brandcolors.net
006400, FF9C2A, FF4025, 3949AB, EFEFEF

It will take a while for the issue to be processed, so please let me know which colors are more dominant and represent the brand freeCodeCamp.

**Comment by erictleung** [comment]
Looks like it is already accepted

![image](https://cloud.githubusercontent.com/assets/2754821/22311322/dd490df8-e307-11e6-9260-ef855814da64.png)

**Comment by QuincyLarson** [comment]
Awesome! Well done!

**Comment by tommygebru** [comment]
No worries @erictleung @dkhamsing is very much responsive to changes to Brandcolors.net
just let me know and I will get on it!

**Comment by tommygebru** [comment]
thanks @QuincyLarson
